### ISSUE TITLE
Is it ok to ...

### ISSUE THREAD

**Issue by nuk** [rogerluan/JobList#12]
Add brazilian companies that hire remote workers like Startae, HELabs and bxblue?
and
Add networks like https://impulso.work/
?

**Comment by rogerluan** [comment]
The network is fine, but the companies nah. Although they serve similar purposes, usually those networks always have open job offers, while the companies may not have open job offers. 
The main purpose of this list is for freelancing (if it's remote, it's a win!), and the network allows freelancing, but not those companies :)
