### ISSUE TITLE
Invalid url's in README.md

### ISSUE THREAD

**Issue by stavares843** [rogerluan/JobList#18]
| 404's  | 
| ------------- | 
https://stackoverflow.com/jobs?type=contract&allowsremote=true?ref=rogeroba 
https://stackoverflow.com/jobs?ref=rogeroba
https://beta.jobmote.com/ref=rogeroba
http://codemill.io/?ref=rogeroba
https://jobs.github.com/positions?ref=rogeroba
https://jobspresso.co/browsejobs?ref=rogeroba

| 403's  | 
| ------------- | 
https://angel.co/job-collections/remote?ref=rogeroba

| Timeout's  | 
| ------------- | 
https://xcodejobs.com/?ref=rogeroba
http://savvyapps.com/?ref=rogeroba
https://www.remotelyawesomejobs.com/?ref=rogeroba
https://localsolo.com/?ref=rogeroba
http://mokriya.com/?ref=rogeroba

**Comment by rogerluan** [comment]
Thank you so much @stavares843 🤗 I've cleaned them up via https://github.com/rogerluan/JobList/commit/bb14ac605c5478c8dca5f82c1b0ffd4d8c1e2d35

💪

**Comment by stavares843** [comment]
🎉
